---
apiVersion: v1
kind: Namespace
metadata:
  name: bakehouse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bakehouse
  name: bakehouse
  namespace: bakehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bakehouse
  template:
    metadata:
      labels:
        app: bakehouse
    spec:
      containers:
      - image: bojy1297/bakehouse:vtag
        name: bakehouse
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
