apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice
  name: myservice
  namespace: bakehouse
spec:
  type: LoadBalancer
  ports:
   - port: 85
     protocol: TCP
     targetPort: 80
  selector:
    app: bakehouse